name: Build and Release APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          app/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x app/gradlew
      
    - name: Build Debug APK
      run: |
        cd app
        ./gradlew assembleDebug
    
    - name: Generate release tag
      id: tag
      run: echo "release_tag=v$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
    
    - name: Create Release with GH CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ steps.tag.outputs.release_tag }} \
          app/app/build/outputs/apk/debug/app-debug.apk \
          --title "SSID Logger Build ${{ steps.tag.outputs.release_tag }}" \
          --notes "Automated build from commit ${{ github.sha }}
        
        Download the APK directly (no unzipping needed).
        
        **Installation:**
        1. Download ssid-logger.apk to your Android device
        2. Open the file and install
        3. Grant permissions when prompted
        
        **Changes:** See [commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})" \
          --latest
        
        # Rename the asset after upload
        gh release edit ${{ steps.tag.outputs.release_tag }} \
          --repo ${{ github.repository }}
        
        echo "### ✅ Release Created!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Direct APK download:** https://github.com/${{ github.repository }}/releases/download/${{ steps.tag.outputs.release_tag }}/app-debug.apk" >> $GITHUB_STEP_SUMMARY