name: Build and Release APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          app/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x app/gradlew
      
    - name: Build Debug APK
      run: |
        cd app
        ./gradlew assembleDebug
      
    - name: Generate release tag
      id: tag
      run: echo "release_tag=build-$(date +%Y%m%d-%H%M%S)-$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        release_name: SSID Logger Build ${{ steps.tag.outputs.release_tag }}
        body: |
          Automated build from commit ${{ github.sha }}
          
          Download the APK below to install on your Android device.
          
          **Installation Instructions:**
          1. Download the APK to your Android device
          2. Open the file (you may need a file manager app)
          3. If prompted, enable "Install from unknown sources" in Settings
          4. Install the app
          
          **Required Permissions:**
          - Location (for WiFi SSID access)
          - Background location (for monitoring when app is closed)
          
          **Note:** This is a debug build for testing purposes.
        draft: false
        prerelease: false
    
    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/app/build/outputs/apk/debug/app-debug.apk
        asset_name: ssid-logger-debug.apk
        asset_content_type: application/vnd.android.package-archive